name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:  # allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true  # need the input files

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r test/requirements.txt

      - name: Install CLM-ml dependencies
        run: |
          sudo apt install libnetcdf-dev libnetcdff-dev libblas-dev liblapack-dev

      - name: Compile the CLM-ml executable
        run: |
          cd exe
          make
          cd ../
          
      - name: Test
        run: python -m pytest
